#pragma once
#include <cstdint>
#include <cstddef>
#include <stdexcept>
#include <cassert>
#include <functional>
#include <utility>
#include <string>
#include <fstream>
#include <algorithm>
#include <chrono>
#include <memory>